name: C/C++ CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    name: Lint clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format lint
        run: find include/ src/ \( -name '*.[ch]pp' -o -name '*.h' \) | xargs clang-format --verbose --style=file -n --Werror

  linting-and-compile-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile and test
        run: |
            cd examples/neutral_example_implementation
            make
      - name: Fail fast if Compile examples fails
        if: ${{ job.status == 'failure' }}
        run: |
          echo "Compile examples failed!"
          exit 1

      # Additional steps if linting and compile examples are successful
